# Generated by Django 5.2.7 on 2025-10-30 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverMaster',
            fields=[
                ('caregiver_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('year_of_joining', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('start_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_sitter', models.CharField(max_length=255)),
                ('background', models.TextField()),
                ('check_status', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='caregiver_photos/')),
            ],
            options={
                'db_table': 'caregiver_master',
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('forgot_password', 'Forgot Password')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'otp_verification',
            },
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_master',
            },
        ),
        migrations.CreateModel(
            name='CaregiverDetail',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('highlights', models.TextField()),
                ('functionality', models.TextField()),
                ('caregiver_id', models.ForeignKey(blank=True, db_column='caregiver_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.caregivermaster')),
            ],
            options={
                'db_table': 'caregiver_detail',
            },
        ),
        migrations.CreateModel(
            name='CaregiverReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('caregiver_id', models.ForeignKey(blank=True, db_column='caregiver_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.caregivermaster')),
            ],
            options={
                'db_table': 'caregiver_review',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('emergency_contact', models.CharField(max_length=255)),
                ('user_condition', models.TextField()),
                ('user_needs', models.TextField()),
                ('user_services', models.TextField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermaster')),
            ],
            options={
                'db_table': 'user_detail',
            },
        ),
        migrations.CreateModel(
            name='UserMemberDetail',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('relation', models.CharField(max_length=50)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermaster')),
            ],
            options={
                'db_table': 'user_member_detail',
            },
        ),
        migrations.CreateModel(
            name='ServicesNeeded',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('help', models.TextField()),
                ('services', models.TextField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermaster')),
                ('member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usermemberdetail')),
            ],
            options={
                'db_table': 'services_needed',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentDetail',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=20)),
                ('expiry_date', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=5)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermaster')),
            ],
            options={
                'db_table': 'user_payment_detail',
            },
        ),
    ]
