# Generated by Django 5.2.5 on 2025-10-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverMaster',
            fields=[
                ('caregiver_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('year_of_joining', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('desc', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('start_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_sitter', models.CharField(max_length=255)),
                ('background', models.TextField()),
                ('check_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverDetail',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('highlights', models.TextField()),
                ('functionality', models.TextField()),
                ('caregiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.caregivermaster')),
            ],
        ),
        migrations.CreateModel(
            name='CaregiverReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewer_name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.caregiverdetail')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('emergency_contact', models.CharField(max_length=255)),
                ('user_condition', models.TextField()),
                ('user_needs', models.TextField()),
                ('user_services', models.TextField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='UserMemberDetail',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('relation', models.CharField(max_length=50)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesNeeded',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('help', models.TextField()),
                ('services', models.TextField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermaster')),
                ('member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usermemberdetail')),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentDetail',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=20)),
                ('expiry_date', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=5)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usermaster')),
            ],
        ),
    ]
