# Generated by Django 5.2.7 on 2025-10-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='caregiverdetail',
            table='caregiver_detail',
        ),
        migrations.AlterModelTable(
            name='caregivermaster',
            table='caregiver_master',
        ),
        migrations.AlterModelTable(
            name='caregiverreview',
            table='caregiver_review',
        ),
        migrations.AlterModelTable(
            name='servicesneeded',
            table='services_needed',
        ),
        migrations.AlterModelTable(
            name='userdetail',
            table='user_detail',
        ),
        migrations.AlterModelTable(
            name='usermaster',
            table='user_master',
        ),
        migrations.AlterModelTable(
            name='usermemberdetail',
            table='user_member_detail',
        ),
        migrations.AlterModelTable(
            name='userpaymentdetail',
            table='user_payment_detail',
        ),
    ]
