# Generated by Django 5.2.5 on 2025-10-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usermaster_updated_at_alter_usermaster_address_1_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermaster',
            table='user_master',
        ),
    ]
